# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: double-quote-string-fixer
      - id: check-docstring-first
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: poetry run safety
        language: python
        language_version: python3.10
        args:
          - check
          - --full-report
        pass_filenames: false
        types: [python]

      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --recursive
          - --ignore-init-module-imports
          - --remove-duplicate-keys
          - --exclude=docs/conf.py,scripts/*
        language: python
        language_version: python3.10
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: python
        language_version: python3.10
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: python
        language_version: python3.10
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: python
        language_version: python3.10
        types: [python]
        exclude: ^alembic/
